I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script
    show ed xpos 1300 ypos 300
Exception: Image 'ed' does not accept attributes 'xpos 1300 ypos 300'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script
    show ed xpos 1300 ypos 300
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'ed' does not accept attributes 'xpos 1300 ypos 300'.

macOS-14.1.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
dongjin_love 1.0
Thu May  9 03:39:37 2024
